#version: '3.9'

services:

  # PostgreSQL
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sakura0moti
      POSTGRES_PASSWORD: music0
      POSTGRES_DB: holomoti
    volumes:
      - postgres_data:/var/lib/postgresql/data # データ永続化
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # 初期スクリプト
    ports:
      - "2000:5432"
      
      
  # JupyterLab
  jupyter:
    build: ./api
    container_name: jupyter
    volumes:
      - ./api:/api
    working_dir: /api
    ports:
      - "8888:8888"
    command:
      uv run jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''

  # Flask API Server
  api:
    build: ./api
    container_name: api
    volumes:
      - ./api:/api
    working_dir: /api
    ports:
      - "5000:5000"
    command:
      uv run python api.py
      
  # Quasar framework webpage
  quasar:
    build: ./ui
    container_name: quasar
    volumes:
      - ./ui:/ui
    working_dir: /ui
    ports:
      - "9000:9000"
    tty: true
      
      
  # Batch services
  batch_twitter_scraping:
    build: ./api
    container_name: batch_twitter_scraping
    volumes:
      - ./api:/batch
    working_dir: /batch
    command:
      uv run /batch/src/batch/twitter_update_batch.py
    profiles:
      - batch  # ← 通常の `docker-compose up` では起動しない
volumes:
  postgres_data: