version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sakura0moti
      POSTGRES_PASSWORD: music0
      POSTGRES_DB: holomoti
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # SQL スクリプトを実行
    ports:
      - "1234:5432"
  api:
    build: ./api
    container_name: api
    volumes:
      - ./api:/api
    working_dir: /api
    ports:
      - "8888:8888"
    command:
      uv run jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
volumes:
  postgres_data: