version: '3'

tasks:
  build:
    desc: コンテナ実行
    cmds:
      - docker compose down
      - docker compose up -d
      
  stop:
    desc: コンテナの停止
    cmds:
      - docker compose stop
      - docker compose down
      
  api-restart:
    desc: APIサーバーを再起動する
    cmds:
      - docker compose stop api
      - docker compose rm api
      - docker compose build --no-cache api
      
  ui-build:
    desc: UIのビルドを実行
    cmds:
      - docker compose run --rm quasar_build
      - rm -rf ./web/dist
      - cp -r ui/dist ./web/dist
      
  deploy:
    desc: apacheサーバーとcloudflaredトンネルを起動
    cmds:
      - task: ui-build
      #- docker stop api cron postgres_db holomoti2-api-tunnel-1 holomoti2-ui-tunnel-1
      #- docker rm api cron postgres_db holomoti2-api-tunnel-1 holomoti2-ui-tunnel-1
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d
      
  stop-deploy:
    desc: deployしたコンテナの停止
    cmds:
      - docker compose stop
      - docker stop holomoti2-ui-tunnel-1 holomoti2-api-tunnel-1 nginx-server
      - docker rm holomoti2-ui-tunnel-1 holomoti2-api-tunnel-1 nginx-server
      - docker compose down
      
  batch-twitter:
    desc: twitterのDBを更新
    cmds:
      - docker compose run --rm batch_twitter_scraping
  
  git-pull:
    desc: 最新バージョンに更新
    cmds:
      - git fetch origin master
      - git reset --hard origin/master
  