version: '3'

tasks:
  build:
    desc: コンテナ再実行
    cmds:
      - docker-compose down
      - docker-compose up -d
      
  stop:
    desc: コンテナの停止
    cmds:
      - docker-compose down
      
  batch-twitter:
    desc: twitterのDBを更新
    cmds:
      - docker compose run --rm batch_twitter_scraping